# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@14.2.0 @nrwl/angular@15.1.1
  displayName: 'npm install Angular CLI and Nx'
- script: |
    npm install
  displayName: 'npm install'

- script: |
    ng build satellite-tracker
  displayName: 'build'

- publish: '$(System.DefaultWorkingDirectory)/dist/apps/satellite-tracker/'
  artifact: app

- script: |
    ng build data-api
  displayName: 'build'

- publish: '$(System.DefaultWorkingDirectory)/dist/apps/data-api/'
  artifact: api