name: Satellite Tracker CI/CD

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'

            - name: Install npm dependencies
              run: |
                  npm ci
            - name: Run satellite-tracker unit tests
              run: |
                  npx nx run satellite-tracker:test
            - name: Run satellite-tracker e2e tests
              uses: cypress-io/github-action@v5.0.5
              with:
                  build: npx nx run satellite-tracker:build
                  start: npx nx run satellite-tracker:serve
                  wait-on: 'http://localhost:4200/'
              # run: |
              #     npx nx run satellite-tracker-e2e:e2e

            - name: 'Deploy to satellite-tracker to Netlify'
              uses: jsmrcaga/action-netlify-deploy@v2.0.0
              with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_TO_PROD: true
                  build_command: 'npm run build'
                  build_directory: 'dist/apps/satellite-tracker'

            - name: Install Railway
              run: npm i -g @railway/cli

            - name: Deploy satellite-tracker-api to Railway
              run: railway up
              env:
                  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
